apiVersion: v1
kind: Service
metadata:
  name: arc-firecracker-controller
  namespace: actions-runner-system
  labels:
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/component: firecracker-api
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
  - name: firecracker-api
    port: 8081
    targetPort: 8081
    nodePort: 30081
    protocol: TCP
  selector:
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/component: controller-manager
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: firecracker-config
  namespace: actions-runner-system
data:
  config.yaml: |
    # Firecracker VM Manager Configuration
    workDir: "/opt/firecracker/data"
    kernelDir: "/opt/firecracker/kernels"
    imagesDir: "/opt/firecracker/images"
    snapshotsDir: "/opt/firecracker/snapshots"
    instancesDir: "/opt/firecracker/instances"
    
    # Default VM configuration
    defaultKernel: "vmlinux-6.1.128-ubuntu24"
    defaultRootfs: "actions-runner-ubuntu-24.04.ext4"
    defaultMemoryMiB: 2048
    defaultVCPUs: 2
    
    # Network configuration
    defaultNetworkConfig:
      interface: "eth0"
      subnetCIDR: "172.16.0.0/24"
      gateway: "172.16.0.1"
      bridgeName: "fc-br0"
      tapDeviceName: "fc-tap0"
    
    # Host bridge configuration (optional)
    hostBridge:
      name: "br0"
      enabled: false
    
    # ARC Integration
    arcControllerURL: "http://localhost:30080" 