apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: firecracker-runners
  namespace: actions-runner-system
  annotations:
    # Firecracker runtime configuration
    runner.summerwind.dev/runtime: "firecracker"
    runner.summerwind.dev/firecracker-kernel: "/opt/firecracker/kernels/vmlinux-5.10"
    runner.summerwind.dev/firecracker-rootfs: "/opt/firecracker/images/ubuntu-runner.ext4"
    runner.summerwind.dev/firecracker-memory: "4096"
    runner.summerwind.dev/firecracker-vcpus: "4"
    runner.summerwind.dev/firecracker-network: '{"interface":"eth0","subnetCIDR":"172.16.0.0/24","gateway":"172.16.0.1"}'
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: firecracker-runner
    spec:
      # Basic runner configuration
      organization: "your-org"  # or repository: "your-org/your-repo" 
      ephemeral: true
      githubAPICredentialsFrom:
        secretRef:
          name: github-pat-secret
      labels:
        - self-hosted
        - firecracker
        - linux
        - x64
      
      # Container specs are ignored when using Firecracker runtime,
      # but kept here for compatibility
      image: "runner:latest"
      resources:
        limits:
          cpu: "4"
          memory: "8Gi"
        requests:
          cpu: "2"
          memory: "4Gi" 