# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  creationTimestamp: "2025-05-29T22:33:40Z"
  generation: 229
  name: tenki-standard-autoscale-31187360
  namespace: tenki-63928428
  resourceVersion: "50405314"
  uid: ba82d56a-f375-4c37-aa29-d4968e54e971
spec:
  effectiveTime: "2025-05-30T08:11:12Z"
  replicas: 0
  selector: null
  template:
    metadata:
      annotations:
        tenki/environment: prod
        tenki/installationId: "63928428"
        tenki/offeringId: 0196ff32-ab8c-7c51-8c5b-6377c7614544
        tenki/repositoryId: "31187360"
        tenki/workspaceId: 0195ee0f-fe08-73db-b517-646dd0c64285
      labels:
        tenki: runner
    spec:
      # Runtime configuration for Firecracker VMs
      runtime:
        type: firecracker
        firecracker:
          kernelImagePath: "/opt/firecracker/kernels/vmlinux-5.10"
          rootfsImagePath: "/opt/firecracker/images/ubuntu-runner.ext4"
          memoryMiB: 4096
          vcpus: 4
          networkConfig:
            interface: eth0
            subnetCIDR: "172.16.0.0/24"
            gateway: "172.16.0.1"
      containers:
      - name: docker
        resources:
          limits:
            cpu: "4"
            memory: 16Gi
          requests:
            cpu: "2"
            memory: 8Gi
        volumeMounts:
        - mountPath: /home/runner
          name: runner-home
        - mountPath: /home/runner/buildkit/buildkitd.toml
          name: cache-config
          subPath: buildkitd.toml
        - mountPath: /etc/docker/daemon.json
          name: cache-config
          subPath: daemon.json
      - env:
        - name: USER
          value: runner
        - name: ACTIONS_RESULTS_URL
          value: http://action-cache.tenki.cloud/
        - name: DISABLE_RUNNER_UPDATE
          value: "true"
        - name: GOPROXY
          value: http://goproxy.tenki.cloud,direct
        image: us-west1-docker.pkg.dev/tenki-cloud/tenki-apps/ubuntu-runner-ubuntu-22.04:6cfe15b-1742664778
        name: runner
        resources:
          limits:
            cpu: "4"
            memory: 16Gi
          requests:
            cpu: "2"
            memory: 8Gi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /home/runner
          name: runner-home
        - mountPath: /home/runner/buildkit/buildkitd.toml
          name: cache-config
          subPath: buildkitd.toml
        - mountPath: /etc/docker/daemon.json
          name: cache-config
          subPath: daemon.json
      dockerdContainerResources: {}
      ephemeral: true
      githubAPICredentialsFrom:
        secretRef:
          name: github-app-runner-secret
      group: Default
      image: ""
      imagePullSecrets:
      - name: tenki-regcred
      initContainers:
      - args:
        - |
          mkdir -p /home/runner/.docker/buildx
          cp /mnt/buildkitd.toml /home/runner/.docker/buildx/buildkitd.default.toml
          chown -R 1001:1001 /home/runner/.docker/*
          chown  1001:1001 /home/runner/.docker
          cp /mnt/.npmrc /home/runner/.npmrc
          chown 1001:1001 /home/runner/.npmrc
        command:
        - sh
        - -c
        image: busybox:1.36
        name: setup-cache-config
        resources: {}
        volumeMounts:
        - mountPath: /mnt/buildkitd.toml
          name: cache-config
          subPath: buildkitd.toml
        - mountPath: /home/runner
          name: runner-home
        - mountPath: /mnt/.npmrc
          name: cache-config
          subPath: .npmrc
      labels:
      - tenki-standard-autoscale
      nodeSelector:
        node-class: fast
      organization: LuxorLabs
      resources: {}
      volumes:
      - emptyDir: {}
        name: runner-home
      - emptyDir: {}
        name: tmp
      - configMap:
          items:
          - key: buildkitd.toml
            path: buildkitd.toml
          - key: daemon.json
            path: daemon.json
          - key: .npmrc
            path: .npmrc
          name: cache-config
        name: cache-config
status:
  availableReplicas: 0
  desiredReplicas: 0
  readyReplicas: 0
  replicas: 0
  updatedReplicas: 0
