---
apiVersion: v1
kind: Namespace
metadata:
  name: actions-runner-system
  labels:
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
  labels:
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/component: service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: actions-runner-controller
  labels:
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/component: cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets", "nodes"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["*"]
- apiGroups: ["actions.summerwind.dev"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: actions-runner-controller
  labels:
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/component: cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: actions-runner-controller
subjects:
- kind: ServiceAccount
  name: actions-runner-controller
  namespace: actions-runner-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: firecracker-config
  namespace: actions-runner-system
  labels:
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/component: config
data:
  firecracker.yaml: |
    firecracker:
      enabled: true
      kernelPath: "/opt/firecracker/kernels/vmlinux"
      rootfsPath: "/opt/firecracker/images/rootfs.ext4"
      defaultMemoryMiB: 2048
      defaultVCPUs: 2
      networkConfig:
        subnet: "172.16.0.0/24"
        bridgeName: "br0"
        tapPrefix: "fc-tap-"
      vmConfig:
        socketPath: "/var/lib/firecracker/vms"
        logPath: "/var/log/firecracker"
---
apiVersion: v1
kind: Service
metadata:
  name: arc-firecracker-service
  namespace: actions-runner-system
  labels:
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/component: nodeport-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/component: controller
  ports:
  - name: webhook-http
    port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
  - name: webhook-https
    port: 8443
    targetPort: 8443
    nodePort: 30081
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
  labels:
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: firecracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: actions-runner-controller
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: actions-runner-controller
        app.kubernetes.io/component: controller
        app.kubernetes.io/version: firecracker
    spec:
      serviceAccountName: actions-runner-controller
      securityContext:
        # Required for Firecracker VM management
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: manager
        image: us-west1-docker.pkg.dev/tenki-cloud/tenki-runners-prod/arc-aakash-no-run:v2.3.2-firecracker
        imagePullPolicy: Always
        command:
        - /manager
        args:
        - --enable-leader-election
        - --sync-period=1m
        - --docker-image=summerwind/actions-runner:latest
        - --runner-image=summerwind/actions-runner:latest
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: controller-manager
              key: github_token
              optional: true
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              name: controller-manager
              key: github_app_id
              optional: true
        - name: GITHUB_APP_INSTALLATION_ID
          valueFrom:
            secretKeyRef:
              name: controller-manager
              key: github_app_installation_id
              optional: true
        - name: GITHUB_APP_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: controller-manager
              key: github_app_private_key
              optional: true
        - name: FIRECRACKER_ENABLED
          value: "true"
        - name: FIRECRACKER_CONFIG_PATH
          value: "/etc/firecracker/firecracker.yaml"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 8080
          name: webhook-http
          protocol: TCP
        - containerPort: 8443
          name: webhook-https
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        securityContext:
          # Firecracker requires privileged access for VM management
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_RESOURCE
        volumeMounts:
        - name: firecracker-config
          mountPath: /etc/firecracker
          readOnly: true
        - name: firecracker-assets
          mountPath: /opt/firecracker
        - name: firecracker-runtime
          mountPath: /var/lib/firecracker
        - name: firecracker-logs
          mountPath: /var/log/firecracker
        - name: tmp-firecracker
          mountPath: /tmp/firecracker
        # Required for VM networking
        - name: dev-kvm
          mountPath: /dev/kvm
        - name: dev-net-tun
          mountPath: /dev/net/tun
      terminationGracePeriodSeconds: 30
      volumes:
      - name: firecracker-config
        configMap:
          name: firecracker-config
      - name: firecracker-assets
        hostPath:
          path: /opt/firecracker
          type: DirectoryOrCreate
      - name: firecracker-runtime
        hostPath:
          path: /var/lib/firecracker
          type: DirectoryOrCreate
      - name: firecracker-logs
        hostPath:
          path: /var/log/firecracker
          type: DirectoryOrCreate
      - name: tmp-firecracker
        emptyDir: {}
      - name: dev-kvm
        hostPath:
          path: /dev/kvm
          type: CharDevice
      - name: dev-net-tun
        hostPath:
          path: /dev/net/tun
          type: CharDevice
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
---
# Example RunnerDeployment with Firecracker runtime
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: firecracker-example-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: your-org/your-repo
      runtime:
        type: firecracker
        firecracker:
          kernelImagePath: "/opt/firecracker/kernels/vmlinux"
          rootfsImagePath: "/opt/firecracker/images/rootfs.ext4" 
          memoryMiB: 2048
          vCPUs: 2
          networkConfig:
            useHostBridge: false
          ephemeralMode: true
          arcMode: true
          arcControllerURL: "http://arc-firecracker-service.actions-runner-system.svc.cluster.local:8080"
      labels:
        - "firecracker"
        - "vm-runner" 