apiVersion: v1
kind: Service
metadata:
  name: firecracker-vm-daemon
  namespace: arc-systems
  labels:
    app: firecracker-daemon
spec:
  type: NodePort
  selector:
    app: firecracker-daemon
  ports:
  - port: 8091
    targetPort: 8091
    nodePort: 30090
    protocol: TCP
    name: vm-agent 