apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: tenki-standard-autoscale-aki-213161010
  namespace: tenki-68130006
  annotations:
    tenki/environment: staging
    tenki/installationId: "68130006"
    tenki/offeringId: 0197010e-1aed-7458-be4e-5446634f56ae
    tenki/repositoryId: "213161010"
    tenki/workspaceId: 0197010e-1a98-7ebb-a4b7-134dec5d4800
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        tenki/environment: staging
        tenki/installationId: "68130006"
        tenki/offeringId: 0197010e-1aed-7458-be4e-5446634f56ae
        tenki/repositoryId: "213161010"
        tenki/workspaceId: 0197010e-1a98-7ebb-a4b7-134dec5d4800
        # Firecracker runtime configuration via annotations
        runner.summerwind.dev/runtime: firecracker
        runner.summerwind.dev/firecracker-arc-mode: "true"
        runner.summerwind.dev/firecracker-arc-url: http://192.168.21.32:30090
        runner.summerwind.dev/firecracker-ephemeral: "true"
        runner.summerwind.dev/firecracker-kernel: /opt/firecracker/kernels/vmlinux-6.1.128-ubuntu24
        runner.summerwind.dev/firecracker-memory: "16384"
        runner.summerwind.dev/firecracker-network: '{"interface":"eth0","networkMode":"bridge","bridgeName":"br0","dhcpEnabled":true}'
        runner.summerwind.dev/firecracker-snapshot: prod-v1
        runner.summerwind.dev/firecracker-vcpus: "4"
      labels:
        tenki: runner
    spec:
      organization: aakash-test-workflow
      labels:
      - tenki-standard-autoscale-aki
      
      group: Default
      
      ephemeral: true
      
      githubAPICredentialsFrom:
        secretRef:
          name: github-app-runner-secret
      
      nodeSelector:
        kubernetes.io/hostname: tenki-staging-runner-2
      
      imagePullSecrets:
      - name: tenki-regcred
      
      # tolerations:
      # - key: "firecracker"
      #   operator: "Equal"
      #   value: "true"
      #   effect: "NoSchedule"
      
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - tenki-staging-runner-2
---
# HorizontalRunnerAutoscaler without problematic fields
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: tenki-standard-autoscale-aki-213161010
  namespace: tenki-68130006
spec:
  githubAPICredentialsFrom:
    secretRef:
      name: github-app-runner-secret
  maxReplicas: 100
  minReplicas: 1
  scaleDownDelaySecondsAfterScaleOut: 10
  scaleTargetRef:
    kind: RunnerDeployment
    name: tenki-standard-autoscale-aki-213161010
  scaleUpTriggers:
  - duration: 10m
    githubEvent:
      workflowJob: {}
